### ISSUE TITLE
Auto-layout

### ISSUE THREAD

**Issue by marckaraujo** [agens-no/AGGeometryKit#42]
When you apply auto-layout and make all constrains, everything broke for crop action.

**Comment by hfossli** [comment]
Do you have any code or examples to clarify your concern?

**Comment by marckaraujo** [comment]
Yes, I just uploaded : https://bitbucket.org/marckaraujo/aggeometrykit

It is your demo app with auto-layout enabled.

**Comment by hfossli** [comment]
Yep, in general applying transforms to views you manage with auto layout is a bad mix.

**Comment by hfossli** [comment]
Thanks for reporting, but this is more of a problem with UIKit than a problem of AGGeometryKit IMHO.
