### ISSUE TITLE
How can I  crop the image by using AGGeometryKit.

### ISSUE THREAD

**Issue by jixuqianxing** [agens-no/AGGeometryKit#43]
<img width="400" alt="image" src="https://cloud.githubusercontent.com/assets/5623436/20779569/46563f74-b7b0-11e6-8bea-94dfbbb0874e.png">

**Comment by hfossli** [comment]
As you point out this is a 2 step process.

1. First you need to change the perspective. Have a look at https://github.com/agens-no/AGGeometryKit/issues/25
2. Then you need to crop the image. Have a look at http://stackoverflow.com/questions/158914/cropping-an-uiimage

Good luck :)

**Comment by jixuqianxing** [comment]
Thank you very much 😄. I get it.
