### ISSUE TITLE
Hello, when i set quadrilateral, the position of the layer is shifted, and how to remove the quadrilateral settings

### ISSUE THREAD

**Issue by EasonGaoDevelop** [agens-no/AGGeometryKit#46]
Hello, when i set quadrilateral, the position of the layer is shifted, how to remove the quadrilateral settings, I use a uiimageview to achieve the quadrilateral deformation function, uiimageview can be dragged within a certain range, but as long as using quadrilateral, Accurate, so i need to remove the quadrilateral settings after the deformation

**Comment by hfossli** [comment]
Hey! Thanks for using our library! Can you share some code? Kind of hard to grasp what you are saying :)

**Comment by EasonGaoDevelop** [comment]
hello， I refer to your demo like this code
self.layer.quadrilateral = AGKQuadMake(self.topLeftControl.center,
                                                   self.topRightControl.center,
                                                   self.bottomRightControl.center,
                                                   self.bottomLeftControl.center);

how to remove  quadrilateral setting

**Comment by EasonGaoDevelop** [comment]
When i set up self.imageView.layer.quadrilateral after the finger drags the imageView out of the screen, I have touched in the touchesMoved method, but it is invalid, and I guess that anchorPoint has changed
![image](https://cloud.githubusercontent.com/assets/12585454/23208998/4a803cb2-f932-11e6-9432-315c015e8f73.png)

**Comment by hfossli** [comment]
Yep, anchor point must be set to 0,0 for the quad to render correctly. Is the blue square on top left your desired result after removing the quadrilateral?

**Comment by EasonGaoDevelop** [comment]
<img width="279" alt="bdaa4d13-e92d-4993-a0b3-50bc33957e40" src="https://cloud.githubusercontent.com/assets/12585454/23209176/1094b766-f933-11e6-8738-f6f132923d75.png">
I need imageView to be dragged in red box exactly, i need to remove the blue box in the top left corner and what should i do

**Comment by hfossli** [comment]
Sorry, there's just too little context and code here for me to help you. Maybe you can zip a demo project showing your problem?

**Comment by EasonGaoDevelop** [comment]
Can you give me your email? I made a zip demo project to you！

**Comment by hfossli** [comment]
Awesome. It's in my bio here https://github.com/hfossli :)

**Comment by hfossli** [comment]
I don't think I have received any mail :)

**Comment by EasonGaoDevelop** [comment]
I'm sorry, I have other things to delay, I will give you a demo mail at tomorrow

**Comment by EasonGaoDevelop** [comment]
Hello, demo has been sent to your hfossli@gmail.com
