### ISSUE TITLE
tvOS

### ISSUE THREAD

**Issue by Loloasis** [agens-no/AGGeometryKit#47]
Can you add support for tvOS on the podspec ?

Thanks.

**Comment by hfossli** [comment]
I don't know if it works on tvOS. Never tried it there. I'd be happy to merge any pull requests :)

**Comment by Loloasis** [comment]
I already use your pod on tvOS but I need to import .h/.m.

I think you should just replace in your podSpec:

-    s.platform      = :ios, '5.0'
+    s.ios.deployment_target = '5.0'
+    s.tvos.deployment_target = '9.0'

I someone can confirm ?
Thanks.

**Comment by hfossli** [comment]
<img width="1095" alt="skjermbilde 2017-05-09 kl 14 11 29" src="https://cloud.githubusercontent.com/assets/3652587/25850141/6dc1e386-34c1-11e7-9b19-8c9d2eac6e51.png">
Fixed

**Comment by hfossli** [comment]
Thanks for reporting :) Please let me know if there's something that doesn't work.
